import '../styles/globals.css';
import Head from 'next/head';
import {AppProps} from "next/app";

function MyApp({Component, pageProps, router}: AppProps): JSX.Element {
  return <>
    <Head>
      <title>My Top</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
      <link rel="preconnect" href="https://fonts.gstatic.com"/>
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap"
            rel="stylesheet"/>
      <meta property="og:url" content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath}/>
      <meta property="og:locale" content="ru"/>
    </Head>

    <Component {...pageProps} />
  </>;
}

export default MyApp;
